# Generated by Django 3.1.7 on 2023-03-12 11:41

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('days', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=0), size=None)),
                ('status', models.BooleanField(default=0)),
                ('voice_message', models.FilePathField()),
                ('time', models.DateTimeField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.FilePathField()),
                ('priority', models.BooleanField(default=0)),
                ('user_type', models.CharField(choices=[('D', 'Dependant'), ('P', 'Protector')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('dependant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependant_relation', to='Backend.user')),
                ('protector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protector_relation', to='Backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('voice_message', models.FilePathField()),
                ('message', models.TextField()),
                ('dependant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependant_message', to='Backend.user')),
                ('protector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protector_message', to='Backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('file_path', models.FilePathField()),
                ('dependant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependant_interface', to='Backend.user')),
                ('protector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protector_interface', to='Backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('activity_type', models.CharField(choices=[('C', 'Call'), ('V', 'Video call'), ('M', 'Message'), ('N', 'Notification')], max_length=20)),
                ('telephone', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('dependant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependant_activity', to='Backend.user')),
                ('protector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protector_activity', to='Backend.user')),
            ],
        ),
    ]
