# Generated by Django 3.1.7 on 2022-10-09 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='phone',
            new_name='telephone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='telephone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login',
        ),
    ]
